packages:
  - apps/*
  - packages/*
  - packages/@repo/*

catalog:
  '@sanity/assist': ^6.1.19
  '@sanity/client': ^7.26.2
  '@sanity/color-input': ^6.1.3
  '@sanity/icons': ^5.2.1
  '@sanity/pkg-utils': ^12.1.2
  '@sanity/tsconfig': 2.2.1
  '@sanity/types': ^6.9.2
  '@sanity/ui': ^4.0.6
  '@sanity/util': ^6.9.2
  '@sanity/vision': ^6.9.2
  '@types/node': ^24.13.3
  '@types/react': ^19.2.18
  '@types/react-dom': ^19.2.4
  babel-plugin-react-compiler: ^1.0.0
  groq: ^6.9.2
  react: ^19.2.8
  react-dom: ^19.2.8
  rxjs: ^7.8.2
  sanity: ^6.9.2
  sanity-plugin-asset-source-unsplash: ^7.0.23
  styled-components: ^6.5.2
  typescript: 6.0.3
  xstate: ^5.32.5

catalogs:
  tailwind3:
    '@tailwindcss/postcss': ^4.3.3
    '@tailwindcss/typography': ^0.5.20
    tailwindcss: ^4.3.3

linkWorkspacePackages: deep

preferWorkspacePackages: true
