packages:
  - apps/*
  - packages/*
  - packages/@repo/*

catalog:
  '@sanity/assist': ^6.1.14
  '@sanity/client': ^7.23.0
  '@sanity/color-input': ^6.0.16
  '@sanity/icons': ^5.1.0
  '@sanity/pkg-utils': ^10.5.7
  '@sanity/tsconfig': 2.2.1
  '@sanity/types': ^6.5.0
  '@sanity/ui': ^3.3.5
  '@sanity/util': ^6.5.0
  '@sanity/vision': ^6.5.0
  '@types/node': ^24.13.3
  '@types/react': ^19.2.17
  '@types/react-dom': ^19.2.3
  '@typescript-eslint/eslint-plugin': ^8.61.0
  '@typescript-eslint/parser': ^8.61.0
  eslint-plugin-react-hooks: ^7.0.1
  groq: ^6.5.0
  react: ^19.2.7
  react-dom: ^19.2.7
  rxjs: ^7.8.2
  sanity: ^6.5.0
  sanity-plugin-asset-source-unsplash: ^7.0.19
  styled-components: ^6.4.3
  typescript: 5.9.3
  babel-plugin-react-compiler: ^1.0.0
  xstate: ^5.32.5

catalogs:
  tailwind3:
    '@tailwindcss/postcss': ^4.3.3
    '@tailwindcss/typography': ^0.5.20
    tailwindcss: ^4.3.3

linkWorkspacePackages: deep

preferWorkspacePackages: true
