packages:
  - apps/*
  - packages/*
  - packages/@repo/*
  - packages/comlink/playground

catalog:
  '@sanity/assist': ^4.4.7
  '@sanity/color-input': ^4.0.5
  '@sanity/cli': ^4.1.0
  '@sanity/client': ^7.8.1
  '@sanity/icons': ^3.7.4
  '@sanity/pkg-utils': ^7.9.8
  '@sanity/types': ^4.1.0
  '@sanity/ui': ^3.0.0
  '@sanity/util': ^4.1.0
  '@sanity/vision': ^4.1.0
  '@types/node': ^24.0.13
  '@types/react': ^19.1.8
  '@types/react-dom': ^19.1.6
  '@typescript-eslint/eslint-plugin': ^8.36.0
  '@typescript-eslint/parser': ^8.36.0
  babel-plugin-react-compiler: 19.1.0-rc.2
  eslint-plugin-react-compiler: 19.1.0-rc.2
  eslint-plugin-react-hooks: 0.0.0-experimental-d55cc79b-20250228
  groq: ^4.1.0
  prettier: ^3.6.2
  react: ^19.1.0
  react-compiler-runtime: 19.1.0-rc.2
  react-dom: ^19.1.0
  react-is: ^19.1.0
  rxjs: ^7.8.2
  sanity: ^4.1.0
  sanity-plugin-asset-source-unsplash: ^3.0.4
  styled-components: ^6.1.19
  typescript: 5.8.3
  use-effect-event: ^2.0.3
  xstate: ^5.20.1

catalogs:
  tailwind3:
    '@tailwindcss/typography': ^0.5.16
    tailwindcss: ^3.4.17
