packages:
  - apps/*
  - packages/*
  - packages/@repo/*

catalog:
  '@sanity/assist': ^5.0.2
  '@sanity/cli': ^5.5.0
  '@sanity/client': ^7.13.2
  '@sanity/color-input': ^6.0.1
  '@sanity/icons': ^3.7.4
  '@sanity/pkg-utils': ^10.2.1
  '@sanity/tsconfig': 2.1.0
  '@sanity/types': ^5.5.0
  '@sanity/ui': ^3.1.11
  '@sanity/util': ^5.5.0
  '@sanity/vision': ^5.5.0
  '@types/node': ^24.0.13
  '@types/react': ^19.2.7
  '@types/react-dom': ^19.2.3
  '@typescript-eslint/eslint-plugin': ^8.36.0
  '@typescript-eslint/parser': ^8.36.0
  eslint-plugin-react-hooks: ^7.0.1
  groq: ^5.5.0
  react: ^19.2.3
  react-dom: ^19.2.3
  rxjs: ^7.8.2
  sanity: ^5.5.0
  sanity-plugin-asset-source-unsplash: ^7.0.0
  styled-components: ^6.1.19
  typescript: 5.9.3
  xstate: ^5.25.0

catalogs:
  tailwind3:
    '@tailwindcss/typography': ^0.5.16
    tailwindcss: ^3.4.17

linkWorkspacePackages: deep

preferWorkspacePackages: true
