packages:
  - apps/*
  - packages/*
  - packages/@repo/*
  - packages/comlink/playground

catalog:
  '@sanity/assist': ^5.0.0
  '@sanity/cli': ^4.10.1
  '@sanity/client': audience-decide
  '@sanity/color-input': ^4.0.6
  '@sanity/icons': ^3.7.4
  '@sanity/pkg-utils': ^8.0.2
  '@sanity/types': https://pkg.pr.new/@sanity/types@51c4c6a
  '@sanity/ui': ^3.0.14
  '@sanity/util': ^4.10.1
  '@sanity/vision': ^4.10.1
  '@types/node': ^24.0.13
  '@types/react': ^19.1.9
  '@types/react-dom': ^19.1.9
  '@typescript-eslint/eslint-plugin': ^8.36.0
  '@typescript-eslint/parser': ^8.36.0
  babel-plugin-react-compiler: 19.1.0-rc.3
  eslint-plugin-react-compiler: 19.1.0-rc.2
  eslint-plugin-react-hooks: 0.0.0-experimental-d55cc79b-20250228
  groq: ^4.10.1
  prettier: ^3.6.2
  react: ^19.1.1
  react-compiler-runtime: 19.1.0-rc.3
  react-dom: ^19.1.1
  react-is: ^19.1.1
  rxjs: ^7.8.2
  sanity: https://pkg.pr.new/sanity@51c4c6a
  sanity-plugin-asset-source-unsplash: ^4.0.1
  styled-components: ^6.1.19
  typescript: 5.9.2
  use-effect-event: ^2.0.3
  xstate: ^5.21.0

catalogs:
  tailwind3:
    '@tailwindcss/typography': ^0.5.16
    tailwindcss: ^3.4.17
