packages:
  - apps/*
  - packages/*
  - packages/@repo/*

catalog:
  '@sanity/assist': ^5.0.4
  '@sanity/cli': ^5.8.1
  '@sanity/client': ^7.14.1
  '@sanity/color-input': ^6.0.4
  '@sanity/icons': ^3.7.4
  '@sanity/pkg-utils': ^10.4.4
  '@sanity/tsconfig': 2.1.0
  '@sanity/types': ^5.8.1
  '@sanity/ui': ^3.1.11
  '@sanity/util': ^5.8.1
  '@sanity/vision': ^5.8.1
  '@types/node': ^24.10.11
  '@types/react': ^19.2.13
  '@types/react-dom': ^19.2.3
  '@typescript-eslint/eslint-plugin': ^8.54.0
  '@typescript-eslint/parser': ^8.54.0
  eslint-plugin-react-hooks: ^7.0.1
  groq: ^5.8.1
  react: ^19.2.4
  react-dom: ^19.2.4
  rxjs: ^7.8.2
  sanity: ^5.8.1
  sanity-plugin-asset-source-unsplash: ^7.0.3
  styled-components: ^6.3.8
  typescript: 5.9.3
  xstate: ^5.26.0

catalogs:
  tailwind3:
    '@tailwindcss/typography': ^0.5.19
    tailwindcss: ^3.4.19

linkWorkspacePackages: deep

preferWorkspacePackages: true
