packages:
  - apps/*
  - packages/*
  - packages/@repo/*

catalog:
  '@sanity/assist': ^5.0.0
  '@sanity/cli': ^4.11.0
  '@sanity/client': ^7.11.2
  '@sanity/color-input': ^4.0.6
  '@sanity/icons': ^3.7.4
  '@sanity/pkg-utils': ^8.1.16
  '@sanity/types': ^4.11.0
  '@sanity/ui': ^3.1.6
  '@sanity/util': ^4.11.0
  '@sanity/vision': ^4.11.0
  '@types/node': ^24.0.13
  '@types/react': ^19.1.8
  '@types/react-dom': ^19.1.6
  '@typescript-eslint/eslint-plugin': ^8.36.0
  '@typescript-eslint/parser': ^8.36.0
  eslint-plugin-react-hooks: 7.0.0
  groq: ^4.11.0
  prettier: ^3.6.2
  react: ^19.1.1
  react-dom: ^19.1.1
  react-is: ^19.1.1
  rxjs: ^7.8.2
  sanity: ^4.11.0
  sanity-plugin-asset-source-unsplash: ^4.0.1
  styled-components: ^6.1.19
  typescript: 5.9.2
  use-effect-event: ^2.0.3
  xstate: ^5.21.0

catalogs:
  tailwind3:
    '@tailwindcss/typography': ^0.5.16
    tailwindcss: ^3.4.17
