import type {Metadata} from 'next'

import {validateApiPerspective, type ClientPerspective} from '@sanity/client'
import {perspectiveCookieName} from '@sanity/preview-url-secret/constants'
import {VercelToolbar} from '@vercel/toolbar/next'
import {revalidatePath, unstable_cache, refresh, revalidateTag} from 'next/cache'
import {cookies, draftMode} from 'next/headers'

import '../../tailwind.css'
import {Timesince} from '../Timesince'
import VisualEditing from './VisualEditing'

export const metadata: Metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export async function actionPerspectiveChange(perspective: ClientPerspective): Promise<void> {
  'use server'

  console.log('actionPerspectiveChange', perspective)

  const {isEnabled} = await draftMode()
  if (!isEnabled) {
    console.warn('Draft mode is not enabled, skipping actionStudioPerspective')
    return
  }
  try {
    validateApiPerspective(perspective)
  } catch (error) {
    console.error('Invalid perspective', error)
    return
  }

  const jar = await cookies()
  const nextPerspective = Array.isArray(perspective) ? perspective.join(',') : perspective
  if (nextPerspective === jar.get(perspectiveCookieName)?.value) {
    console.log('Perspective is the same, skipping', {
      perspective,
      nextPerspective,
      prevPerspective: jar.get(perspectiveCookieName)?.value,
    })
    return
  }

  jar.set(perspectiveCookieName, nextPerspective, {
    httpOnly: true,
    path: '/',
    secure: true,
    sameSite: 'none',
  })

  refresh()
}

export default async function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="en">
      <body>
        {children}
        <VercelToolbar />
        {(await draftMode()).isEnabled && (
          <VisualEditing
            onPerspectiveChange={actionPerspectiveChange}
            refresh={async (payload) => {
              'use server'
              if (!(await draftMode()).isEnabled) {
                console.error('Draft Mode is not enabled, ignoring refresh')
                return
              }
              if (payload.source === 'manual') {
                console.log('Revalidating everything')
                return revalidatePath('/only-visual-editing', 'layout')
              }
              if (payload.source === 'mutation') {
                if (payload.document.slug?.current) {
                  const tag = `${payload.document._type}:${payload.document.slug.current}`
                  console.log('Revalidate slug', tag)
                  await revalidateTag(tag, {expire: 0})
                }
                console.log('Revalidate tag', payload.document._type)
                return revalidateTag(payload.document._type, {expire: 0})
              }
            }}
          />
        )}
        <a className="fixed bottom-1 left-1 block rounded bg-slate-900 px-2 py-1 text-xs text-slate-100">
          app-router:{' '}
          {(await draftMode()).isEnabled
            ? 'draftMode'
            : process.env.NEXT_PUBLIC_VERCEL_ENV || 'development'}
          {', '}
          <span className="text-slate-300">
            served: <Timesince since={await getCachedServed()} />
          </span>
        </a>
      </body>
    </html>
  )
}

const getCachedServed = unstable_cache(
  async () => new Date().toJSON(),
  ['only-visual-editing-test'],
  {tags: ['served']},
)
