export {createOverlayController} from './controller'
export {
  type DocumentStoreState,
  useOptimisticStateSelector,
  useOptimisticStateStore,
} from './ui/optimistic-state/optimisticState'
export type {
  DisableVisualEditing,
  ElementFocusedState,
  ElementState,
  HistoryAdapter,
  HistoryAdapterNavigate,
  HistoryRefresh,
  HistoryUpdate,
  Msg,
  OverlayController,
  OverlayEventHandler,
  OverlayMsg,
  OverlayMsgActivate,
  OverlayMsgBlur,
  OverlayMsgDeactivate,
  OverlayMsgElement,
  OverlayMsgElementActivate,
  OverlayMsgElementClick,
  OverlayMsgElementContextMenu,
  OverlayMsgElementDeactivate,
  OverlayMsgElementMouseEnter,
  OverlayMsgElementMouseLeave,
  OverlayMsgElementRegister,
  OverlayMsgElementUnregister,
  OverlayMsgElementUpdate,
  OverlayMsgElementUpdateRect,
  OverlayMsgUpdateDragCursorPosition,
  OverlayMsgUpdateDragInsertPosition,
  OverlayOptions,
  OverlayRect,
  SanityNode,
  SanityStegaNode,
  VisualEditingOptions,
  VisualEditingOverlayComponent,
} from './types'
export {enableVisualEditing} from './ui/enableVisualEditing'
export {
  type CreateDataAttribute,
  createDataAttribute,
  type CreateDataAttributeProps,
  type WithRequired,
} from '@repo/visual-editing-helpers'
