import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import VisualEditing from './VisualEditing'
import { SanityLoaderProvider } from './sanity.loader'
import { token } from './sanity.server'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SanityLoaderProvider token={token}>{children}</SanityLoaderProvider>
      </body>
      <VisualEditing />
    </html>
  )
}
