/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol

// Source: node_modules/@repo/sanity-extracted-schema/page-builder-demo.json
export type SanityImageAssetReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
}

export type Image1 = {
  asset?: SanityImageAssetReference
  media?: unknown // Unable to locate the referenced type "media" in schema
  hotspot?: SanityImageHotspot
  crop?: SanityImageCrop
  _type: 'image'
}

export type Rotations = {
  pitch?: number
  yaw?: number
}

export type Image2 = {
  asset?: SanityImageAssetReference
  media?: unknown // Unable to locate the referenced type "image.media" in schema
  hotspot?: SanityImageHotspot
  crop?: SanityImageCrop
  _type: 'image'
}

export type PageSectionReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'page.section'
}

export type Section = {
  _type: 'section'
  symbol?: PageSectionReference
  headline?: string
  tagline?: string
  subline?: string
}

export type SectionStyle = {
  _type: 'sectionStyle'
  variant?: 'default' | 'inverted'
}

export type ProductReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'product'
}

export type FeatureHighlight = {
  _type: 'featureHighlight'
  headline?: string
  description?: string
  image?: Image2
  ctas?: Array<{
    title?: string
    href?: string
    _type: 'cta'
    _key: string
  }>
  product?: ProductReference
  style?: SectionStyle
}

export type FeaturedProducts = {
  _type: 'featuredProducts'
  headline?: string
  description?: string
  products?: Array<
    {
      _key: string
    } & ProductReference
  >
  style?: SectionStyle
}

export type Intro = {
  _type: 'intro'
  headline?: string
  intro?: string
  style?: SectionStyle
  rotations?: Rotations
}

export type Hero = {
  _type: 'hero'
  headline?: string
  tagline?: string
  subline?: string
  image?: Image1
  style?: SectionStyle
}

export type PageReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'page'
}

export type SiteSettings = {
  _id: string
  _type: 'siteSettings'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  description?: string
  frontPage?: PageReference
  copyrightText?: string
}

export type Project = {
  _id: string
  _type: 'project'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  slug?: Slug
}

export type Slug = {
  _type: 'slug'
  current?: string
  source?: string
}

export type Page = {
  _id: string
  _type: 'page'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  slug?: Slug
  sections?: Array<
    | {
        headline?: string
        tagline?: string
        subline?: string
        image?: Image1
        style?: SectionStyle
        _type: 'hero'
        _key: string
      }
    | {
        headline?: string
        intro?: string
        style?: SectionStyle
        rotations?: Rotations
        _type: 'intro'
        _key: string
      }
    | {
        headline?: string
        description?: string
        products?: Array<
          {
            _key: string
          } & ProductReference
        >
        style?: SectionStyle
        _type: 'featuredProducts'
        _key: string
      }
    | {
        headline?: string
        description?: string
        image?: Image2
        ctas?: Array<{
          title?: string
          href?: string
          _type: 'cta'
          _key: string
        }>
        product?: ProductReference
        style?: SectionStyle
        _type: 'featureHighlight'
        _key: string
      }
    | {
        symbol?: PageSectionReference
        headline?: string
        tagline?: string
        subline?: string
        _type: 'section'
        _key: string
      }
  >
}

export type PageSection = {
  _id: string
  _type: 'page.section'
  _createdAt: string
  _updatedAt: string
  _rev: string
  headline?: string
  tagline?: string
  subline?: string
}

export type Product = {
  _id: string
  _type: 'product'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  slug?: Slug
  media?: Array<{
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
    _key: string
  }>
  description?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  brandReference?: unknown
  details?: {
    materials?: string
    collectionNotes?: Array<{
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }>
      style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
      listItem?: 'bullet' | 'number'
      markDefs?: Array<{
        href?: string
        _type: 'link'
        _key: string
      }>
      level?: number
      _type: 'block'
      _key: string
    }>
    performance?: Array<{
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }>
      style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
      listItem?: 'bullet' | 'number'
      markDefs?: Array<{
        href?: string
        _type: 'link'
        _key: string
      }>
      level?: number
      _type: 'block'
      _key: string
    }>
    ledLifespan?: string
    certifications?: Array<string>
  }
  variants?: Array<{
    title?: string
    price?: string
    sku?: string
    _type: 'variant'
    _key: string
  }>
}

export type SanityImageCrop = {
  _type: 'sanity.imageCrop'
  top?: number
  bottom?: number
  left?: number
  right?: number
}

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot'
  x?: number
  y?: number
  height?: number
  width?: number
}

export type DndTestPage = {
  _id: string
  _type: 'dndTestPage'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  children?: Array<{
    title?: string
    childrenStrings?: Array<string>
    children?: Array<{
      title?: string
      children?: Array<{
        title?: string
        _type: 'dndTestItemChildL2'
        _key: string
      }>
      _type: 'dndTestItemChildL1'
      _key: string
    }>
    _type: 'dndTestItem'
    _key: string
  }>
}

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch'
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: 'sanity.imagePalette'
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions'
  height?: number
  width?: number
  aspectRatio?: number
}

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata'
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  thumbHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type SanityFileAsset = {
  _id: string
  _type: 'sanity.fileAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  source?: SanityAssetSourceData
}

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData'
  name?: string
  id?: string
  url?: string
}

export type SanityImageAsset = {
  _id: string
  _type: 'sanity.imageAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type Geopoint = {
  _type: 'geopoint'
  lat?: number
  lng?: number
  alt?: number
}

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | Image1
  | Rotations
  | Image2
  | PageSectionReference
  | Section
  | SectionStyle
  | ProductReference
  | FeatureHighlight
  | FeaturedProducts
  | Intro
  | Hero
  | PageReference
  | SiteSettings
  | Project
  | Slug
  | Page
  | PageSection
  | Product
  | SanityImageCrop
  | SanityImageHotspot
  | DndTestPage
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint

// Source: src/app/dnd/page.tsx
// Variable: dndPageQuery
// Query: *[_type == "dndTestPage"]{    _id,    title,    children  }[0]
export type DndPageQueryResult = {
  _id: string
  title: string | null
  children: Array<{
    title?: string
    childrenStrings?: Array<string>
    children?: Array<{
      title?: string
      children?: Array<{
        title?: string
        _type: 'dndTestItemChildL2'
        _key: string
      }>
      _type: 'dndTestItemChildL1'
      _key: string
    }>
    _type: 'dndTestItem'
    _key: string
  }> | null
} | null

// Source: src/app/draft-mode-status.tsx
// Variable: statusQuery
// Query: *[_id == "siteSettings"][0]{_id}
export type StatusQueryResult = {
  _id: 'siteSettings'
} | null

// Query TypeMap
import '@sanity/client'
declare module '@sanity/client' {
  interface SanityQueries {
    '\n  *[_type == "dndTestPage"]{\n    _id,\n    title,\n    children\n  }[0]\n': DndPageQueryResult
    '*[_id == "siteSettings"][0]{_id}': StatusQueryResult
  }
}
